# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Blog | Guangyuan (Charlie) Yang
name: "Guangyuan (Charlie) Yang"
email: yzgyyang@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  My thoughts gathering place.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.charlieyang.me" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: yzgyyang
github_username:  yzgyyang

# Author settings
author:
  name     : "Guangyuan Yang"
  avatar   : "/assets/images/bio-photo.jpg"
  bio      : "Welcome to my thoughts gathering place."
  location : Waterloo, ON
  email    : yzgyyang@outlook.com
  uri      : "http://charlieyang.me"

# Build settings
markdown: kramdown
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed

# Pagination
paginate: 5
paginate_path: /page:num/

# Breadcrumbs
breadcrumbs: true  # disabled by default
breadcrumb_home_label : "Blog"
breadcrumb_separator  : "/"

# Permalink
permalink: /:categories/:year:month/:title.html # default: /:categories/:year/:month/:day/:title.html

# Enable comments for all posts
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      comments: true

# Enable Disqus
comments:
  provider: "disqus"
  disqus:
    shortname: "yzgyyang"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
